name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: echo "Hello World"
      - name: Goobye Step
        run: echo "Goood bye"
